// Code generated by github.com/gofunct/hack/tools. DO NOT EDIT.

// +build tools

package _snapshots_mod

// tool dependencies
import (
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger"
	_ "github.com/haya14busa/reviewdog/cmd/reviewdog"
	_ "golang.org/x/lint/golint"
)

