// Code generated by github.com/gofunct/hack. DO NOT EDIT.

package server

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	foo_pb "testapp/api/foo"
)

// RegisterWithServer implements hackserver.Server.RegisterWithServer.
func (s *barServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	foo_pb.RegisterBarServiceServer(grpcSvr, s)
}

// RegisterWithHandler implements hackserver.Server.RegisterWithHandler.
func (s *barServiceServerImpl) RegisterWithHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return foo_pb.RegisterBarServiceHandler(ctx, mux, conn)
}

