// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package gencmd

import (
	"github.com/gofunct/hack/pkg/cli"
	"github.com/gofunct/hack/pkg/hackcmd"
)

// Injectors from wire.go:

func newApp(command *Command) (*App, error) {
	ctx := ProvideCtx(command)
	hackcmdCtx := ProvideGrapiCtx(ctx)
	fs := hackcmd.ProvideFS(hackcmdCtx)
	io := hackcmd.ProvideIO(hackcmdCtx)
	ui := cli.UIInstance(io)
	rootDir := hackcmd.ProvideRootDir(hackcmdCtx)
	fileSystem := ProvideTemplateFS(command)
	shouldRunFunc := ProvideShouldRun(command)
	generator := NewGenerator(fs, ui, rootDir, fileSystem, shouldRunFunc)
	app := &App{
		Generator: generator,
		UI:        ui,
	}
	return app, nil
}
