// Code generated by protoc-gen-cobra.
// source: token_service/token_service.proto
// DO NOT EDIT!

/*
Package token_service is a generated protocol buffer package.

It is generated from these files:
	token_service/token_service.proto

It has these top-level commands:
	TokenClientCommand
*/

package token_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	cobra "github.com/spf13/cobra"
	context "golang.org/x/net/context"
	credentials "google.golang.org/grpc/credentials"
	envconfig "github.com/kelseyhightower/envconfig"
	filepath "path/filepath"
	grpc "google.golang.org/grpc"
	io "io"
	iocodec "github.com/fiorix/protoc-gen-cobra/iocodec"
	ioutil "io/ioutil"
	json "encoding/json"
	log "log"
	net "net"
	oauth "google.golang.org/grpc/credentials/oauth"
	oauth2 "golang.org/x/oauth2"
	os "os"
	pflag "github.com/spf13/pflag"
	template "text/template"
	time "time"
	tls "crypto/tls"
	x509 "crypto/x509"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ cobra.Command
var _ context.Context
var _ credentials.AuthInfo
var _ envconfig.Decoder
var _ filepath.WalkFunc
var _ grpc.ClientConn
var _ io.Reader
var _ iocodec.Encoder
var _ = ioutil.Discard
var _ json.Encoder
var _ log.Logger
var _ net.IP
var _ oauth.TokenSource
var _ oauth2.Token
var _ os.File
var _ pflag.FlagSet
var _ template.Template
var _ time.Time
var _ tls.Config
var _ x509.Certificate

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

var _DefaultTokenClientCommandConfig = _NewTokenClientCommandConfig()

type _TokenClientCommandConfig struct {
	ServerAddr         string        `envconfig:"SERVER_ADDR" default:"localhost:8080"`
	RequestFile        string        `envconfig:"REQUEST_FILE"`
	PrintSampleRequest bool          `envconfig:"PRINT_SAMPLE_REQUEST"`
	ResponseFormat     string        `envconfig:"RESPONSE_FORMAT" default:"json"`
	Timeout            time.Duration `envconfig:"TIMEOUT" default:"10s"`
	TLS                bool          `envconfig:"TLS"`
	ServerName         string        `envconfig:"TLS_SERVER_NAME"`
	InsecureSkipVerify bool          `envconfig:"TLS_INSECURE_SKIP_VERIFY"`
	CACertFile         string        `envconfig:"TLS_CA_CERT_FILE"`
	CertFile           string        `envconfig:"TLS_CERT_FILE"`
	KeyFile            string        `envconfig:"TLS_KEY_FILE"`
	AuthToken          string        `envconfig:"AUTH_TOKEN"`
	AuthTokenType      string        `envconfig:"AUTH_TOKEN_TYPE" default:"Bearer"`
	JWTKey             string        `envconfig:"JWT_KEY"`
	JWTKeyFile         string        `envconfig:"JWT_KEY_FILE"`
}

func _NewTokenClientCommandConfig() *_TokenClientCommandConfig {
	c := &_TokenClientCommandConfig{}
	envconfig.Process("", c)
	return c
}

func (o *_TokenClientCommandConfig) AddFlags(fs *pflag.FlagSet) {
	fs.StringVarP(&o.ServerAddr, "server-addr", "s", o.ServerAddr, "server address in form of host:port")
	fs.StringVarP(&o.RequestFile, "request-file", "f", o.RequestFile, "client request file (must be json, yaml, or xml); use \"-\" for stdin + json")
	fs.BoolVarP(&o.PrintSampleRequest, "print-sample-request", "p", o.PrintSampleRequest, "print sample request file and exit")
	fs.StringVarP(&o.ResponseFormat, "response-format", "o", o.ResponseFormat, "response format (json, prettyjson, yaml, or xml)")
	fs.DurationVar(&o.Timeout, "timeout", o.Timeout, "client connection timeout")
	fs.BoolVar(&o.TLS, "tls", o.TLS, "enable tls")
	fs.StringVar(&o.ServerName, "tls-server-name", o.ServerName, "tls server name override")
	fs.BoolVar(&o.InsecureSkipVerify, "tls-insecure-skip-verify", o.InsecureSkipVerify, "INSECURE: skip tls checks")
	fs.StringVar(&o.CACertFile, "tls-ca-cert-file", o.CACertFile, "ca certificate file")
	fs.StringVar(&o.CertFile, "tls-cert-file", o.CertFile, "client certificate file")
	fs.StringVar(&o.KeyFile, "tls-key-file", o.KeyFile, "client key file")
	fs.StringVar(&o.AuthToken, "auth-token", o.AuthToken, "authorization token")
	fs.StringVar(&o.AuthTokenType, "auth-token-type", o.AuthTokenType, "authorization token type")
	fs.StringVar(&o.JWTKey, "jwt-key", o.JWTKey, "jwt key")
	fs.StringVar(&o.JWTKeyFile, "jwt-key-file", o.JWTKeyFile, "jwt key file")
}

var TokenClientCommand = &cobra.Command{
	Use: "token",
}

func _DialToken() (*grpc.ClientConn, TokenClient, error) {
	cfg := _DefaultTokenClientCommandConfig
	opts := []grpc.DialOption{
		grpc.WithBlock(),
		grpc.WithTimeout(cfg.Timeout),
	}
	if cfg.TLS {
		tlsConfig := &tls.Config{}
		if cfg.InsecureSkipVerify {
			tlsConfig.InsecureSkipVerify = true
		}
		if cfg.CACertFile != "" {
			cacert, err := ioutil.ReadFile(cfg.CACertFile)
			if err != nil {
				return nil, nil, fmt.Errorf("ca cert: %v", err)
			}
			certpool := x509.NewCertPool()
			certpool.AppendCertsFromPEM(cacert)
			tlsConfig.RootCAs = certpool
		}
		if cfg.CertFile != "" {
			if cfg.KeyFile == "" {
				return nil, nil, fmt.Errorf("missing key file")
			}
			pair, err := tls.LoadX509KeyPair(cfg.CertFile, cfg.KeyFile)
			if err != nil {
				return nil, nil, fmt.Errorf("cert/key: %v", err)
			}
			tlsConfig.Certificates = []tls.Certificate{pair}
		}
		if cfg.ServerName != "" {
			tlsConfig.ServerName = cfg.ServerName
		} else {
			addr, _, _ := net.SplitHostPort(cfg.ServerAddr)
			tlsConfig.ServerName = addr
		}
		//tlsConfig.BuildNameToCertificate()
		cred := credentials.NewTLS(tlsConfig)
		opts = append(opts, grpc.WithTransportCredentials(cred))
	} else {
		opts = append(opts, grpc.WithInsecure())
	}
	if cfg.AuthToken != "" {
		cred := oauth.NewOauthAccess(&oauth2.Token{
			AccessToken: cfg.AuthToken,
			TokenType:   cfg.AuthTokenType,
		})
		opts = append(opts, grpc.WithPerRPCCredentials(cred))
	}
	if cfg.JWTKey != "" {
		cred, err := oauth.NewJWTAccessFromKey([]byte(cfg.JWTKey))
		if err != nil {
			return nil, nil, fmt.Errorf("jwt key: %v", err)
		}
		opts = append(opts, grpc.WithPerRPCCredentials(cred))
	}
	if cfg.JWTKeyFile != "" {
		cred, err := oauth.NewJWTAccessFromFile(cfg.JWTKeyFile)
		if err != nil {
			return nil, nil, fmt.Errorf("jwt key file: %v", err)
		}
		opts = append(opts, grpc.WithPerRPCCredentials(cred))
	}
	conn, err := grpc.Dial(cfg.ServerAddr, opts...)
	if err != nil {
		return nil, nil, err
	}
	return conn, NewTokenClient(conn), nil
}

type _TokenRoundTripFunc func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error

func _TokenRoundTrip(sample interface{}, fn _TokenRoundTripFunc) error {
	cfg := _DefaultTokenClientCommandConfig
	var em iocodec.EncoderMaker
	var ok bool
	if cfg.ResponseFormat == "" {
		em = iocodec.DefaultEncoders["json"]
	} else {
		em, ok = iocodec.DefaultEncoders[cfg.ResponseFormat]
		if !ok {
			return fmt.Errorf("invalid response format: %q", cfg.ResponseFormat)
		}
	}
	if cfg.PrintSampleRequest {
		return em.NewEncoder(os.Stdout).Encode(sample)
	}
	var d iocodec.Decoder
	if cfg.RequestFile == "" || cfg.RequestFile == "-" {
		d = iocodec.DefaultDecoders["json"].NewDecoder(os.Stdin)
	} else {
		f, err := os.Open(cfg.RequestFile)
		if err != nil {
			return fmt.Errorf("request file: %v", err)
		}
		defer f.Close()
		ext := filepath.Ext(cfg.RequestFile)
		if len(ext) > 0 && ext[0] == '.' {
			ext = ext[1:]
		}
		dm, ok := iocodec.DefaultDecoders[ext]
		if !ok {
			return fmt.Errorf("invalid request file format: %q", ext)
		}
		d = dm.NewDecoder(f)
	}
	conn, client, err := _DialToken()
	if err != nil {
		return err
	}
	defer conn.Close()
	return fn(client, d, em.NewEncoder(os.Stdout))
}

var _TokenAllowanceClientCommand = &cobra.Command{
	Use:  "allowance",
	Long: "Allowance client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	allowance -p > req.json

Submit request using file:
	allowance -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | allowance --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v AllowanceReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.Allowance(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenAllowanceClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenAllowanceClientCommand.Flags())
}

var _TokenApproveClientCommand = &cobra.Command{
	Use:  "approve",
	Long: "Approve client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	approve -p > req.json

Submit request using file:
	approve -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | approve --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v ApproveReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.Approve(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenApproveClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenApproveClientCommand.Flags())
}

var _TokenApproveAndCallClientCommand = &cobra.Command{
	Use:  "approveandcall",
	Long: "ApproveAndCall client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	approveandcall -p > req.json

Submit request using file:
	approveandcall -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | approveandcall --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v ApproveAndCallReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.ApproveAndCall(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenApproveAndCallClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenApproveAndCallClientCommand.Flags())
}

var _TokenBalanceOfClientCommand = &cobra.Command{
	Use:  "balanceof",
	Long: "BalanceOf client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	balanceof -p > req.json

Submit request using file:
	balanceof -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | balanceof --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v BalanceOfReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.BalanceOf(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenBalanceOfClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenBalanceOfClientCommand.Flags())
}

var _TokenBurnClientCommand = &cobra.Command{
	Use:  "burn",
	Long: "Burn client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	burn -p > req.json

Submit request using file:
	burn -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | burn --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v BurnReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.Burn(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenBurnClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenBurnClientCommand.Flags())
}

var _TokenBurnFromClientCommand = &cobra.Command{
	Use:  "burnfrom",
	Long: "BurnFrom client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	burnfrom -p > req.json

Submit request using file:
	burnfrom -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | burnfrom --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v BurnFromReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.BurnFrom(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenBurnFromClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenBurnFromClientCommand.Flags())
}

var _TokenDecimalsClientCommand = &cobra.Command{
	Use:  "decimals",
	Long: "Decimals client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	decimals -p > req.json

Submit request using file:
	decimals -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | decimals --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v Empty
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.Decimals(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenDecimalsClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenDecimalsClientCommand.Flags())
}

var _TokenNameClientCommand = &cobra.Command{
	Use:  "name",
	Long: "Name client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	name -p > req.json

Submit request using file:
	name -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | name --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v Empty
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.Name(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenNameClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenNameClientCommand.Flags())
}

var _TokenSymbolClientCommand = &cobra.Command{
	Use:  "symbol",
	Long: "Symbol client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	symbol -p > req.json

Submit request using file:
	symbol -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | symbol --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v Empty
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.Symbol(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenSymbolClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenSymbolClientCommand.Flags())
}

var _TokenTotalSupplyClientCommand = &cobra.Command{
	Use:  "totalsupply",
	Long: "TotalSupply client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	totalsupply -p > req.json

Submit request using file:
	totalsupply -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | totalsupply --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v Empty
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.TotalSupply(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenTotalSupplyClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenTotalSupplyClientCommand.Flags())
}

var _TokenTransferClientCommand = &cobra.Command{
	Use:  "transfer",
	Long: "Transfer client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	transfer -p > req.json

Submit request using file:
	transfer -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | transfer --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v TransferReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.Transfer(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenTransferClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenTransferClientCommand.Flags())
}

var _TokenTransferFromClientCommand = &cobra.Command{
	Use:  "transferfrom",
	Long: "TransferFrom client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	transferfrom -p > req.json

Submit request using file:
	transferfrom -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | transferfrom --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v TransferFromReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.TransferFrom(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenTransferFromClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenTransferFromClientCommand.Flags())
}

var _TokenOnApprovalClientCommand = &cobra.Command{
	Use:  "onapproval",
	Long: "OnApproval client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	onapproval -p > req.json

Submit request using file:
	onapproval -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | onapproval --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v OnApprovalReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.OnApproval(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenOnApprovalClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenOnApprovalClientCommand.Flags())
}

var _TokenOnBurnClientCommand = &cobra.Command{
	Use:  "onburn",
	Long: "OnBurn client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	onburn -p > req.json

Submit request using file:
	onburn -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | onburn --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v OnBurnReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.OnBurn(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenOnBurnClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenOnBurnClientCommand.Flags())
}

var _TokenOnTransferClientCommand = &cobra.Command{
	Use:  "ontransfer",
	Long: "OnTransfer client\n\nYou can use environment variables with the same name of the command flags.\nAll caps and s/-/_, e.g. SERVER_ADDR.",
	Example: `
Save a sample request to a file (or refer to your protobuf descriptor to create one):
	ontransfer -p > req.json

Submit request using file:
	ontransfer -f req.json

Authenticate using the Authorization header (requires transport security):
	export AUTH_TOKEN=your_access_token
	export SERVER_ADDR=api.example.com:443
	echo '{json}' | ontransfer --tls`,
	Run: func(cmd *cobra.Command, args []string) {
		var v OnTransferReq
		err := _TokenRoundTrip(v, func(cli TokenClient, in iocodec.Decoder, out iocodec.Encoder) error {

			err := in.Decode(&v)
			if err != nil {
				return err
			}

			resp, err := cli.OnTransfer(context.Background(), &v)

			if err != nil {
				return err
			}

			return out.Encode(resp)

		})
		if err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	TokenClientCommand.AddCommand(_TokenOnTransferClientCommand)
	_DefaultTokenClientCommandConfig.AddFlags(_TokenOnTransferClientCommand.Flags())
}
