// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/gofunct/hack/pkg/cli"
	"github.com/gofunct/hack/pkg/excmd"
	"github.com/gofunct/hack/pkg/hackcmd"
	"github.com/gofunct/hack/pkg/hackcmd/internal/module"
	"github.com/gofunct/hack/pkg/hackcmd/internal/usecase"
	"github.com/gofunct/hack/pkg/protoc"
	"github.com/gofunct/hack/pkg/tool"
)

// Injectors from wire.go:

func NewUI(ctx *hackcmd.Ctx) cli.UI {
	io := hackcmd.ProvideIO(ctx)
	ui := cli.UIInstance(io)
	return ui
}

func NewCommandExecutor(ctx *hackcmd.Ctx) excmd.Executor {
	io := hackcmd.ProvideIO(ctx)
	executor := excmd.NewExecutor(io)
	return executor
}

func NewGenerator(ctx *hackcmd.Ctx) module.Generator {
	io := hackcmd.ProvideIO(ctx)
	ui := cli.UIInstance(io)
	generator := ProvideGenerator(ctx, ui)
	return generator
}

func NewScriptLoader(ctx *hackcmd.Ctx) module.ScriptLoader {
	io := hackcmd.ProvideIO(ctx)
	executor := excmd.NewExecutor(io)
	scriptLoader := ProvideScriptLoader(ctx, executor)
	return scriptLoader
}

func NewToolRepository(ctx *hackcmd.Ctx) (tool.Repository, error) {
	fs := hackcmd.ProvideFS(ctx)
	execInterface := hackcmd.ProvideExecer(ctx)
	io := hackcmd.ProvideIO(ctx)
	rootDir := hackcmd.ProvideRootDir(ctx)
	config := protoc.ProvideGexConfig(fs, execInterface, io, rootDir)
	repository, err := protoc.ProvideToolRepository(config)
	if err != nil {
		return nil, err
	}
	return repository, nil
}

func NewProtocWrapper(ctx *hackcmd.Ctx) (protoc.Wrapper, error) {
	config := hackcmd.ProvideProtocConfig(ctx)
	fs := hackcmd.ProvideFS(ctx)
	execInterface := hackcmd.ProvideExecer(ctx)
	io := hackcmd.ProvideIO(ctx)
	ui := cli.UIInstance(io)
	rootDir := hackcmd.ProvideRootDir(ctx)
	toolsConfig := protoc.ProvideGexConfig(fs, execInterface, io, rootDir)
	repository, err := protoc.ProvideToolRepository(toolsConfig)
	if err != nil {
		return nil, err
	}
	wrapper := protoc.NewWrapper(config, fs, execInterface, ui, repository, rootDir)
	return wrapper, nil
}

func NewInitializeProjectUsecase(ctx *hackcmd.Ctx) usecase.InitializeProjectUsecase {
	fs := hackcmd.ProvideFS(ctx)
	execInterface := hackcmd.ProvideExecer(ctx)
	io := hackcmd.ProvideIO(ctx)
	rootDir := hackcmd.ProvideRootDir(ctx)
	config := protoc.ProvideGexConfig(fs, execInterface, io, rootDir)
	ui := cli.UIInstance(io)
	generator := ProvideGenerator(ctx, ui)
	initializeProjectUsecase := ProvideInitializeProjectUsecase(ctx, config, ui, generator)
	return initializeProjectUsecase
}
