// Code generated by github.com/gofunct/hack/tools. DO NOT EDIT.

// +build tools

package _snapshots_dep

// tool dependencies
import (
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"
)

