// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package testing

import (
	"github.com/gofunct/hack/pkg/cli"
	"github.com/gofunct/hack/pkg/gencmd"
	"github.com/gofunct/hack/pkg/hackcmd"
)

// Injectors from wire.go:

func NewTestApp(command *gencmd.Command, ui cli.UI) (*gencmd.App, error) {
	ctx := gencmd.ProvideCtx(command)
	hackcmdCtx := gencmd.ProvideGrapiCtx(ctx)
	fs := hackcmd.ProvideFS(hackcmdCtx)
	rootDir := hackcmd.ProvideRootDir(hackcmdCtx)
	fileSystem := gencmd.ProvideTemplateFS(command)
	shouldRunFunc := gencmd.ProvideShouldRun(command)
	generator := gencmd.NewGenerator(fs, ui, rootDir, fileSystem, shouldRunFunc)
	app := &gencmd.App{
		Generator: generator,
		UI:        ui,
	}
	return app, nil
}
